#!/bin/sh

# Checkout the real 'master' so we can view the repo files
here=`pwd`
working_dir=`echo "$here" | sed 's/\/.git$//g'`
repo_script="$working_dir/.pushand"
output=`git --work-tree=$working_dir checkout -b foo master 2>&1`
has_error=`echo "$output" | grep 'already exists'`
if [ -z "$has_error" ]; then
	echo 'Checked out master branch'
else
	echo 'Merging latest changes'
	git --work-tree=$working_dir merge master
fi

# If the repository has a file called '.pushand' then run it
if [ -x "$repo_script" ]; then
	exec "$repo_script"
fi

# JumpBox for Ruby on Rails

# If /var/data/app/old doesn't exist, we haven't deployed an application yet
if [ ! -d /var/data/app/old ]; then
	echo 'Default application still enabled.  Disabling.'
	echo "Enabling new application: $working_dir"
	mv /var/data/app/current /var/data/app/old
else
	echo 'Application already deployed'
fi

# Passenger no longer likes symlinks so we copy the repo to /var/data/app/current (for now).
# Ideally, we would just symlink.
echo 'Updating application'
rsync -ra $working_dir/ /var/data/app/current

# If the app doesn't have a config/database.yml, let's add one from the old application
if [ ! -f /var/data/app/current/config/database.yml ]; then
        mkdir -p /var/data/app/current/config
        cp /var/data/app/old/config/database.yml /var/data/app/current/config/database.yml
fi

echo 'Restarting application'
mkdir -p /var/data/app/current/tmp
touch /var/data/app/current/tmp/restart.txt
