#! /bin/bash
#
# PHD Server: script to create a git repository
#

directory="$1"
here="$(dirname $0)"

if [[ ! -d "$directory" ]]; then
	mkdir -p "$directory" > /dev/null 2>&1
	cd "$directory"       > /dev/null 2>&1
	git init --bare       > /dev/null 2>&1
fi

$here/phd_server_setup_hooks "$directory"
