#! /bin/bash
#
# script to setup the current machine as a phd server
#

path=$(which git-receive-pack)
dir=$(dirname $path)
alias_to="$dir/git-receive-pack_original"
here="$(dirname $0)"
our_version="$here/git-receive-pack"

echo "path:  $path"
echo "dir:   $dir"
echo "alias: $alias_to"
echo "here:  $here"

if [[ -f "$alias_to" ]]; then
	echo "$alias_to already exists - server has already been setup?"
else
	mv $path $alias_to
	cp $our_version $path
fi
